version: '3.8'

services:
  mysql_products_service:
    image: mysql:latest
    container_name: products_db_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql